import express from "express";
import { PORT } from "./config/env.js";
import { loginRouter } from "./Router/login.js";
import dotenv from "dotenv";
import cookieParser from "cookie-parser";
import signupRouter from "./Router/signup.js";
import verifyAccountRouter from "./Router/verifyAccount.js";
import regenerateOtp from "./Router/regenerateOtp.js";
import verifyPhonNumberRouter from "./Router/verifyPhonNumber.js";
import regenerateOtpPhoneNumber from "./Router/regenerateOtpPhone.js";
import askForChangePasswordRouter from "./Router/askForChangePassword.js";
import verifyChangePasswordRouter from "./Router/verifyChangePassword.js";
import changePassword from "./Router/changePassword.js";
import acceptidentityRouter from "./Router/acceptIdentity.js";
import reqCreateStore from "./Router/reqCreateStore.js";
import verifyStorePhoneNumberRouter from "./Router/verifyStorePhonNumber.js";
import bot from "./lib/bot.js";
import askForIdentityImageVerifier from "./Router/askForIdentityImageVerifie.js";
import logoutRouter from "./Router/logout.js";
import regenerateOtpStorePhone from "./Router/regenerateOtpStorePhone.js";
import acceptStore from "./Router/acceptStore.js";
dotenv.config();
const app = express();
app.use("/uploads", express.static("uploads"));
app.use(cookieParser());
app.use(express.json());
app.use("/api/v1/login", loginRouter);
app.use("/api/v1/signup", signupRouter);
app.use("/api/v1/verify-account", verifyAccountRouter);
app.use("/api/v1/verify-phon-number", verifyPhonNumberRouter);
app.use("/api/v1/regenerate-otp", regenerateOtp);
app.use("/api/v1/regenerate-Otp-Phone-Number", regenerateOtpPhoneNumber);
app.use("/api/v1/ask-for-change-password", askForChangePasswordRouter);
app.use("/api/v1/verify-change-password-router", verifyChangePasswordRouter);
app.use("/api/v1/change-password", changePassword);
app.use("/api/v1/ask-for-identity-image-verifier", askForIdentityImageVerifier);
app.use("/api/v1/accept-identity", acceptidentityRouter);
app.use("/api/v1/logout", logoutRouter);
app.use("/api/v1/req-create-store", reqCreateStore);
app.use("/api/v1/verify-store-phone-number", verifyStorePhoneNumberRouter);
app.use("/api/v1/regenerate-otp-store-phone", regenerateOtpStorePhone);
app.use("/api/v1/accept-store", acceptStore);

app.get("/", (req, res) => {
  res.send("Server is running");
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
